# 9/09/2022

# Computer vision
# Random moduli

# Muallif: Farrux Sotivoldiyev

# Numpy ichidagi random moduli
* np.random.seed(x) - x ga biror bir son bersak np.random.random ni shu songa bog'lab qo'yadi va bir xil son qaytaraveradi
* np.random.random() - son yozsak o'shancha istalgan sonni bitta list qilib qaytaradi. Ichiga shape ham yozsak bo'ladi
* np.random.random_sample() -son yozsak o'shancha istalgan sonni bitta list qilib qaytaradi. Ichiga shape ham yozsa bo'ladi
* np.random.choice() - ixtiyoriy elementni tanlab olish uchun ishlatiladi
* np.random.shuffle() - listning ichini chalkashtirib tashlaydi

In [207]:
import numpy as np

**`np.random.seed and np.random.random`**

In [55]:
np.random.seed(19)
np.random.random()

0.09753360174945158

In [62]:
np.random.random(5)

array([0.75015615, 0.28683049, 0.70937606, 0.06478678, 0.68985848])

In [222]:
np.random.random((3,4,3))

array([[[0.61184959, 0.91225608, 0.54161063],
        [0.37394509, 0.01320063, 0.82931769],
        [0.81656153, 0.07972012, 0.1716753 ],
        [0.83814903, 0.56416028, 0.34978221]],

       [[0.14500296, 0.09851908, 0.56018142],
        [0.71006589, 0.95087103, 0.74805133],
        [0.37224601, 0.75847731, 0.07107351],
        [0.62184537, 0.72071403, 0.04180862]],

       [[0.39524182, 0.16133882, 0.27608308],
        [0.22650332, 0.30468393, 0.13623338],
        [0.69425006, 0.0528662 , 0.5814383 ],
        [0.17972813, 0.50669135, 0.28151884]]])

**`np.random.random_sample`**

In [210]:
np.random.random_sample(5)

array([0.44067788, 0.14809125, 0.32003399, 0.03032587, 0.887067  ])

In [216]:
np.random.seed(13)
np.random.random_sample((2,3,4))

array([[[0.77770241, 0.23754122, 0.82427853, 0.9657492 ],
        [0.97260111, 0.45344925, 0.60904246, 0.77552651],
        [0.64161334, 0.72201823, 0.03503652, 0.29844947]],

       [[0.05851249, 0.85706094, 0.37285403, 0.67984795],
        [0.25627995, 0.34758122, 0.00941277, 0.35833378],
        [0.94909418, 0.21789901, 0.31939137, 0.91777239]]])

**`np.random.choice`**

In [63]:
x = np.array([1,2,3,4,5,6,7,8,9])

In [110]:
np.random.choice(x) # x o'zgaruvchining ichidan bittasini tanlab qaytaradi

2

In [108]:
np.random.choice(5) # 5 gacha bo'lgan sonlardan bittasini tanlab qaytaradi

4

In [203]:
np.random.choice(x,size=(3,4))

array([[3, 6, 1, 4],
       [3, 9, 5, 2],
       [2, 1, 8, 5]])

**`np.random.shuffle`** - seed shuffle ga tasir qila olmaydi

In [204]:
y = np.array([12,2,34,4,5,6,76,8,90])

In [205]:
np.random.shuffle(y)

In [206]:
y

array([ 5,  6, 90, 76, 34,  4,  2, 12,  8])